# Generated by Django 4.1.2 on 2022-10-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('code_emp', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name_emp', models.CharField(max_length=40)),
                ('last_name_emp', models.CharField(max_length=40)),
                ('job_emp', models.CharField(max_length=40)),
                ('work_area_emp', models.CharField(max_length=40)),
            ],
        ),
    ]
