# Generated by Django 4.1.2 on 2022-10-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code_product', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=40)),
                ('description_product', models.CharField(max_length=50)),
                ('existence', models.IntegerField()),
                ('brand', models.CharField(max_length=40)),
            ],
        ),
    ]
