# Generated by Django 4.1.2 on 2022-10-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costomer',
            fields=[
                ('code_cost', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name_cost', models.CharField(max_length=40)),
                ('last_name_cost', models.CharField(max_length=40)),
                ('phone_number_cost', models.IntegerField()),
                ('email_cost', models.EmailField(max_length=254)),
            ],
        ),
    ]
